name: Gradle Package Testing

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 7.4.2
        cache-read-only:  ${{ github.ref != 'refs/heads/develop' }}

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      shell: bash

    - name: Build
      uses: gradle/gradle-build-action@v2
      with:
        arguments: >-
          --stacktrace
          :module_a:assembleRelease

    # The USERNAME and TOKEN need to correspond to the credentials environment variables used in
    # the publishing section of your build.gradle
    - name: Publish to GitHub Packages
      uses: gradle/gradle-build-action@v2
      with:
        arguments: >-
          :module_a:publish
      env:
        GITHUB_USERNAME: ${{ github.actor }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
